import { Recipe, EpisodeSubmission, OperatorProfile, PayoutRecord } from "./types";

export const MOCK_OPERATOR: OperatorProfile = {
  id: "OP-042",
  username: "Sarah K.",
  name: "Sarah Kendall",
  email: "sarah.k@example.com",
  phone: "+1 (555) 019-2834",
  badge: "Top Earner",
  payoutMethod: "Bank Transfer",
  bankAccountLast4: "9482",
  uploadOverWifiOnly: true,
  saveOriginalVideo: false,
  emailNotifications: true,
  pushNotifications: true,
  approvedRate: 96.4,
  totalEarnings: 28450.0,
  lastActive: "Active Now",
};

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "rec-dish-01",
    code: "REC-DW-104",
    title: "Load Dishwasher - Kitchen A",
    environment: "Household",
    hardwareRig: "ALOHA Dual-Arm Bimanual",
    estimatedTime: "45s - 65s",
    payoutRate: 22.5,
    description:
      "Grasp mixed ceramic plates, bowls, and cutlery from sink staging area and rack securely into lower dishwasher bay without contact shock > 12N.",
    targetFps: 30,
    expectedDurationSec: 55,
    acceptanceRate: 97.2,
    difficulty: "Intermediate",
    requiredObjects: ["Ceramic plates", "Bowls", "Forks & Knives", "Dishwasher rack"],
    tags: ["Bimanual", "Rigid Object", "Contact Rich"],
  },
  {
    id: "rec-surg-02",
    code: "REC-MED-302",
    title: "Surgical Tool Handover - Dual Arm",
    environment: "Clinical",
    hardwareRig: "Franka Emika Research Dual-Arm",
    estimatedTime: "30s - 45s",
    payoutRate: 38.0,
    description:
      "Precision spatial orientation handover of sterile scalpel and forceps with smooth non-jerking kinematic trajectory and < 2mm tool tip clearance.",
    targetFps: 60,
    expectedDurationSec: 38,
    acceptanceRate: 94.8,
    difficulty: "Expert",
    requiredObjects: ["Micro-forceps", "Sterile Tray", "Scalpel Replica"],
    tags: ["High Precision", "Clinical", "Sub-Millimeter"],
  },
  {
    id: "rec-cloth-03",
    code: "REC-TXT-089",
    title: "Cloth Folding - Deformable Towel",
    environment: "Household",
    hardwareRig: "ALOHA Bimanual Soft-Grip",
    estimatedTime: "50s - 80s",
    payoutRate: 26.0,
    description:
      "Dual-corner tension pull, alignment fold along central longitudinal axis, followed by double transverse fold on cotton waffle towel.",
    targetFps: 30,
    expectedDurationSec: 65,
    acceptanceRate: 95.1,
    difficulty: "Intermediate",
    requiredObjects: ["Cotton Towel (40x80cm)", "Mat Flat Surface"],
    tags: ["Deformable", "Dynamic Cloth", "Dual-Arm"],
  },
  {
    id: "rec-bin-04",
    code: "REC-IND-511",
    title: "Bin Picking - Shiny Metallic Parts",
    environment: "Industrial",
    hardwareRig: "UR5e + Robotiq 2F-85 Gripper",
    estimatedTime: "25s - 40s",
    payoutRate: 18.5,
    description:
      "Segment specular reflective bolts and aluminum brackets in deep tote bin under variable high-glare LED lighting conditions.",
    targetFps: 30,
    expectedDurationSec: 32,
    acceptanceRate: 98.4,
    difficulty: "Beginner",
    requiredObjects: ["Anodized Bolts", "Deep Metal Bin", "Sorting Kitting Box"],
    tags: ["Industrial", "High Specular", "Single-Arm"],
  },
  {
    id: "rec-cable-05",
    code: "REC-WIR-214",
    title: "Cable Routing - Server Chassis Bay B",
    environment: "Warehouse",
    hardwareRig: "ALOHA Dual-Arm Needle-Nose",
    estimatedTime: "60s - 90s",
    payoutRate: 34.0,
    description:
      "Thread flexible Cat6A shielded cable through 3 chassis retention grommets with minimal bending radius preservation (> 25mm).",
    targetFps: 30,
    expectedDurationSec: 72,
    acceptanceRate: 91.5,
    difficulty: "Expert",
    requiredObjects: ["Cat6A Cable", "Server Rack Chassis", "Retention Clips"],
    tags: ["Cable Dynamics", "Occlusion", "Fine Dexterity"],
  },
  {
    id: "rec-fruit-06",
    code: "REC-AGR-401",
    title: "Soft Fruit Harvesting - Heirloom Tomatoes",
    environment: "Agriculture",
    hardwareRig: "Kinova Gen3 + Fin-Ray Gripper",
    estimatedTime: "35s - 50s",
    payoutRate: 21.0,
    description:
      "Stem twisting and gentle pluck of ripe vine tomatoes with adaptive grasp force (< 3.5N) to eliminate bruising.",
    targetFps: 30,
    expectedDurationSec: 42,
    acceptanceRate: 96.0,
    difficulty: "Beginner",
    requiredObjects: ["Vine Plant Replica", "Silicone Tomatoes", "Padded Harvest Crate"],
    tags: ["Soft Grasp", "Agricultural", "Force Sensitive"],
  },
];

export const MOCK_SUBMISSIONS: EpisodeSubmission[] = [
  {
    id: "EP-8942-01",
    recipeId: "rec-dish-01",
    recipeTitle: "Load Dishwasher - Kitchen A",
    environment: "Household",
    submittedAt: "2026-08-04 21:44:12",
    durationSeconds: 58.4,
    totalFrames: 1752,
    rgbSize: 2240000000, // 2.24 GB
    depthSize: 1890000000, // 1.89 GB
    kinematicsSize: 142000000, // 142 MB
    totalSize: 4272000000,
    status: "APPROVED",
    qaScore: 98,
    qaReviewer: "Video Review Team",
    qaFeedback: "Great job! The camera remained stable and the entire dishwasher loading process was clearly visible in the frame.",
    s3Hash: "sha256:7f4c9a18e28d4...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 3.8,
  },
  {
    id: "EP-8941-02",
    recipeId: "rec-surg-02",
    recipeTitle: "Surgical Tool Handover - Dual Arm",
    environment: "Clinical",
    submittedAt: "2026-08-04 20:15:30",
    durationSeconds: 39.2,
    totalFrames: 2352,
    rgbSize: 2650000000,
    depthSize: 2100000000,
    kinematicsSize: 195000000,
    totalSize: 4945000000,
    status: "APPROVED",
    qaScore: 95,
    qaReviewer: "Clinical QA Team",
    qaFeedback: "Excellent stability. The handover of the tools was clear and the tools never left the frame.",
    s3Hash: "sha256:3a91bb480df2a...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 4.1,
  },
  {
    id: "EP-8940-03",
    recipeId: "rec-cable-05",
    recipeTitle: "Cable Routing - Server Chassis Bay B",
    environment: "Warehouse",
    submittedAt: "2026-08-04 18:50:04",
    durationSeconds: 74.0,
    totalFrames: 2220,
    rgbSize: 2410000000,
    depthSize: 1980000000,
    kinematicsSize: 168000000,
    totalSize: 4558000000,
    status: "PENDING",
    qaReviewer: "In Review Queue",
    qaFeedback: "Automated checks passed. Waiting for a human reviewer to verify the cable routing was done correctly.",
    s3Hash: "sha256:88bc2f0091ca3...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 3.5,
  },
  {
    id: "EP-8939-04",
    recipeId: "rec-cloth-03",
    recipeTitle: "Cloth Folding - Deformable Towel",
    environment: "Household",
    submittedAt: "2026-08-04 17:12:45",
    durationSeconds: 66.8,
    totalFrames: 2004,
    rgbSize: 2180000000,
    depthSize: 1720000000,
    kinematicsSize: 154000000,
    totalSize: 4054000000,
    status: "APPROVED",
    qaScore: 97,
    qaReviewer: "Video Review Team",
    qaFeedback: "Both hands were clearly visible and the towel was folded exactly as the instructions described.",
    s3Hash: "sha256:0d18fe9307ab1...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 4.0,
  },
  {
    id: "EP-8938-05",
    recipeId: "rec-bin-04",
    recipeTitle: "Bin Picking - Shiny Metallic Parts",
    environment: "Industrial",
    submittedAt: "2026-08-04 15:40:19",
    durationSeconds: 31.5,
    totalFrames: 945,
    rgbSize: 1890000000,
    depthSize: 1450000000,
    kinematicsSize: 98000000,
    totalSize: 3438000000,
    status: "REJECTED",
    qaScore: 42,
    qaReviewer: "Quality Assurance",
    rejectionReason: "Camera movement was too shaky to clearly identify the metallic parts.",
    qaFeedback: "Rejected: Please mount your phone on a tripod or stable surface during this task, as the heavy shaking caused the video to be unreadable.",
    s3Hash: "sha256:bb104781cae93...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 12.8,
  },
  {
    id: "EP-8937-06",
    recipeId: "rec-dish-01",
    recipeTitle: "Load Dishwasher - Kitchen A",
    environment: "Household",
    submittedAt: "2026-08-04 14:02:11",
    durationSeconds: 52.1,
    totalFrames: 1563,
    rgbSize: 2050000000,
    depthSize: 1680000000,
    kinematicsSize: 130000000,
    totalSize: 3860000000,
    status: "APPROVED",
    qaScore: 99,
    qaReviewer: "Video Review Team",
    qaFeedback: "Perfect lighting and clear visibility of the plates.",
    s3Hash: "sha256:442af88190ced...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 3.4,
  },
  {
    id: "EP-8936-07",
    recipeId: "rec-fruit-06",
    recipeTitle: "Soft Fruit Harvesting - Heirloom Tomatoes",
    environment: "Agriculture",
    submittedAt: "2026-08-04 12:20:55",
    durationSeconds: 44.0,
    totalFrames: 1320,
    rgbSize: 1920000000,
    depthSize: 1540000000,
    kinematicsSize: 110000000,
    totalSize: 3570000000,
    status: "PENDING",
    qaReviewer: "Quality Assurance",
    qaFeedback: "Video is clear. Waiting for review on whether the tomatoes were handled gently enough.",
    s3Hash: "sha256:190afb73e843c...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 4.4,
  },
  {
    id: "EP-8935-08",
    recipeId: "rec-surg-02",
    recipeTitle: "Surgical Tool Handover - Dual Arm",
    environment: "Clinical",
    submittedAt: "2026-08-04 10:48:33",
    durationSeconds: 41.0,
    totalFrames: 2460,
    rgbSize: 2710000000,
    depthSize: 2200000000,
    kinematicsSize: 202000000,
    totalSize: 5112000000,
    status: "REJECTED",
    qaScore: 58,
    qaReviewer: "Clinical QA Team",
    rejectionReason: "Heavy glare from the stainless steel tray made the tools impossible to see.",
    qaFeedback: "Please adjust your overhead lighting so the glare doesn't reflect directly into the camera lens.",
    s3Hash: "sha256:aa99824c0ef71...",
    rigId: "RIG-042-ALPHA",
    teleopLatencyMs: 4.8,
  },
];

export const MOCK_PAYOUTS: PayoutRecord[] = [
  {
    id: "PAY-2026-W31",
    period: "Jul 28 - Aug 03, 2026",
    episodesCount: 142,
    approvedCount: 138,
    grossAmount: 3410.0,
    status: "PAID",
    paidDate: "Aug 04, 2026",
    transactionRef: "ACH-WIRE-884920194",
  },
  {
    id: "PAY-2026-W30",
    period: "Jul 21 - Jul 27, 2026",
    episodesCount: 160,
    approvedCount: 154,
    grossAmount: 3820.0,
    status: "PAID",
    paidDate: "Jul 28, 2026",
    transactionRef: "ACH-WIRE-879104822",
  },
  {
    id: "PAY-2026-W29",
    period: "Jul 14 - Jul 20, 2026",
    episodesCount: 135,
    approvedCount: 130,
    grossAmount: 3190.0,
    status: "PAID",
    paidDate: "Jul 21, 2026",
    transactionRef: "ACH-WIRE-872019472",
  },
  {
    id: "PAY-2026-W32-CURR",
    period: "Aug 04 - Current (In Progress)",
    episodesCount: 18,
    approvedCount: 16,
    grossAmount: 4890.0,
    status: "PROCESSING",
    paidDate: "Estimated Aug 11, 2026",
    transactionRef: "PENDING_CYCLE_CLOSE",
  },
];
